local ICONPATH = "__robotarmy__/graphics/icons/"

data:extend(
{
  {
    type = "item-subgroup",
    name = "robotarmy-droids",
    group = "combat",
    order = "c-2"
  },
  {
    type = "item",
    name = "basic-constructor",
    icon = ICONPATH .. "droid_repair.png",
    icon_size = 64,
    flags = {},
    place_result = "basic-constructor",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-a",
  },
  {
    type = "item",
    name = "droid-rifle",
    icon = ICONPATH .. "droid_rifle.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-rifle",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-b",
  },
  {
    type = "item",
    name = "droid-smg",
    icon = ICONPATH .. "droid_smg.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-smg",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-c",
  },
  {
    type = "item",
    name = "droid-rocket",
    icon = ICONPATH .. "droid_rocket.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-rocket",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-d",
  },
  {
    type = "item",
    name = "droid-flame",
    icon = ICONPATH .. "droid_flame.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-flame",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-e",
  },
  {
    type = "item",
    name = "terminator",
    icon = ICONPATH .. "droid_terminator.png",
    icon_size = 64,
    flags = {},
    place_result = "terminator",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-f",
  },
  {
    type = "item",
    name = "defender-unit",
    icon = ICONPATH .. "defender_unit.png",
    icon_size = 64,
    flags = {},
    place_result = "defender-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-g",
  },
  {
    type = "item",
    name = "distractor-unit",
    icon = ICONPATH .. "distractor_unit.png",
    icon_size = 64,
    flags = {},
    place_result = "distractor-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-h",
  },
  {
    type = "item",
    name = "destroyer-unit",
    icon = ICONPATH .. "destroyer_unit.png",
    icon_size = 64,
    flags = {},
    place_result = "destroyer-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-i",
  },
  {
    type = "item",
    name = "patrol-pole",
    icon = ICONPATH .. "patrol-pole.png",
    icon_size = 64,
    flags = {},
    place_result = "patrol-pole",
    stack_size = 50,
    subgroup = "robotarmy-droids",
    order = "z[droid]-j",
  },

--------------BUILDINGS-------------


  {
    type = "item",
    name = "droid-assembling-machine",
    icon_size = 64,
    icon = ICONPATH .. "droid-assembling-machine.png",
    flags = {},
    place_result = "droid-assembling-machine",
    stack_size = 50,
    subgroup = "production-machine",
    order = "e[robotarmy]-a[droid-assembling-machine]",
  },
  {
    type = "item",
    name = "droid-guard-station",
    icon_size = 64,
    icon = ICONPATH .. "droid-guard-station.png",
    flags = {},
    place_result = "droid-guard-station",
    stack_size = 50,
    subgroup = "production-machine",
    order = "e[robotarmy]-b[droid-guard-station]",
  },
  {
    type = "item",
    name = "construction-warehouse",
    icon_size = 64,
    icon = ICONPATH .. "droid-construction_warehouse.png",
    flags = { },
    place_result = "construction-warehouse",
    stack_size = 50,
    subgroup = "production-machine",
    order = "e[robotarmy]-c[construction-warehouse]",
  },


  {
    type = "item",
    name = "droid-counter",
    icon_size = 64,
    icon = ICONPATH .. "droid-counter.png",
    flags = {},
    place_result = "droid-counter",
    stack_size = 50,
    subgroup = "circuit-network",
    order = "b[combinators]-e[droid-counter]",
  },
  {
    type = "item",
    name = "droid-settings",
    icon_size = 64,
    icon = ICONPATH .. "droid-settings.png",
    flags = {},
    place_result = "droid-settings",
    stack_size = 50,
    subgroup = "circuit-network",
    order = "b[combinators]-e[droid-settings]",
  },
  {
    type = "item",
    name = "loot-chest",
    icon_size = 64,
    icon = ICONPATH .. "loot-chest.png",
    flags = {},
    place_result = "loot-chest",
    stack_size = 50,
    subgroup = "storage",
    order = "a[items]-c[loot-chest]",
  },


  {
  -- This allows loading the selection-tool type item when mods are removed
    type = "selection-tool",
    name = "droid-selection-tool",
    icon_size = 64,
    icon = ICONPATH .. "selection_tool.png",
    flags = {},
    subgroup = "tool",
    order = "d[droid-control]-s[selection]",
    stack_size = 1,
    stackable = false,
    selection_color = { r = 0, g = 1, b = 0 },
    alt_selection_color = { r = 0, g = 1, b = 0 },
    selection_mode = {"same-force"},
    alt_selection_mode = {"same-force"},
    selection_cursor_box_type = "not-allowed",
    alt_selection_cursor_box_type = "not-allowed",
  },
  {
  -- This allows loading the selection-tool type item when mods are removed
    type = "selection-tool",
    name = "droid-pickup-tool",
    icon_size = 64,
    icon = ICONPATH .. "pickup_tool.png",
    flags = {},
    subgroup = "tool",
    order = "d[droid-control]-p[pickup]",
    stack_size = 1,
    stackable = false,
    selection_color = { r = 1, g = 0, b = 0 },
    alt_selection_color = { r = 1, g = 0, b = 0 },
    selection_mode = {"blueprint"},
    alt_selection_mode = {"blueprint"},
    selection_cursor_box_type = "not-allowed",
    alt_selection_cursor_box_type = "not-allowed",
  }
})