local ICONPATH = "__robotarmy__/graphics/icons/"

local a =
{
  {
    type = "item-subgroup",
    name = "robotarmy-droids",
    group = "combat",
    order = "c-2",
  },

  {
    type = "recipe-category",
    name = "droids",
  },

  {
    type = "item",
    name = "droid-rifle",
    icon = ICONPATH .. "droid_rifle_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-rifle",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-b",
  },
  {
    type = "item",
    name = "droid-smg",
    icon = ICONPATH .. "droid_smg_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-smg",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-c",
  },
  {
    type = "item",
    name = "droid-rocket",
    icon = ICONPATH .. "droid_rocket_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-rocket",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-d",
  },
  {
    type = "item",
    name = "droid-flame",
    icon = ICONPATH .. "droid_flame_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "droid-flame",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-e",
  },
  {
    type = "item",
    name = "terminator",
    icon = ICONPATH .. "terminator_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "terminator",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-f",
  },
  {
    type = "item",
    name = "defender-unit",
    icon = ICONPATH .. "defender_unit_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "defender-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-g",
  },
  {
    type = "item",
    name = "distractor-unit",
    icon = ICONPATH .. "distractor_unit_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "distractor-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-h",
  },
  {
    type = "item",
    name = "destroyer-unit",
    icon = ICONPATH .. "destroyer_unit_undep.png",
    icon_size = 64,
    flags = {},
    place_result = "destroyer-unit",
    stack_size = 25,
    subgroup = "robotarmy-droids",
    order = "z[droid]-i",
  },
  {
    type = "item",
    name = "patrol-pole",
    icon = ICONPATH .. "patrol-pole.png",
    icon_size = 64,
    flags = {},
    place_result = "patrol-pole",
    stack_size = 50,
    subgroup = "robotarmy-droids",
    order = "z[droid]-j",
  },




  {
    type = "item",
    name = "terminator-dummy",
    icon_size = 64,
    icon = ICONPATH .. "terminator.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "droid-rocket-dummy",
    icon_size = 64,
    icon = ICONPATH .. "droid_rocket.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "droid-rifle-dummy",
    icon_size = 64,
    icon = ICONPATH .. "droid_rifle.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "droid-flame-dummy",
    icon_size = 64,
    icon = ICONPATH .. "droid_flame.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "droid-smg-dummy",
    icon_size = 64,
    icon = ICONPATH .. "droid_smg.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "defender-unit-dummy",
    icon_size = 64,
    icon = ICONPATH .. "defender.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "distractor-unit-dummy",
    icon_size = 64,
    icon = ICONPATH .. "distractor.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },
  {
    type = "item",
    name = "destroyer-unit-dummy",
    icon_size = 64,
    icon = ICONPATH .. "destroyer.png",
    flags = {},
    order = "z-z",
    subgroup = "capsule",
    place_result = "",
    stack_size = 1,
  },

  {
    type = "item",
    name = "droid-assembling-machine",
    icon_size = 64,
    icon = ICONPATH .. "droid-assembling-machine.png",
    flags =  {},
    subgroup = "production-machine",
    order = "b[droid-assembling-machine]",
    place_result = "droid-assembling-machine",
    stack_size = 50,
  },
  {
    type = "item",
    name = "droid-guard-station",
    icon_size = 64,
    icon = ICONPATH .. "droid-guard-station.png",
    flags =  {},
    subgroup = "production-machine",
    order = "b[droid-guard-station]",
    place_result = "droid-guard-station",
    stack_size = 50,
  },
  {
    type = "item",
    name = "droid-counter",
    icon_size = 64,
    icon = ICONPATH .. "droid-counter.png",
    flags =  {},
    subgroup = "circuit-network",
    place_result="droid-counter",
    order = "b[combinators]-e[droid-counter]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "droid-settings",
    icon_size = 64,
    icon = ICONPATH .. "droid-settings.png",
    flags =  {},
    subgroup = "circuit-network",
    place_result="droid-settings",
    order = "b[combinators]-e[droid-settings]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "loot-chest",
    icon_size = 64,
    icon = ICONPATH .. "loot-chest.png",
    flags =  {},
    subgroup = "storage",
    place_result="loot-chest",
    order = "a[items]-c[loot-chest]",
    stack_size = 50,
  },
  {
    -- This allows loading the selection-tool type item when mods are removed
    type = "selection-tool",
    name = "droid-selection-tool",
    icon_size = 64,
    icon = ICONPATH .. "selection_tool.png",
    flags =  {"only-in-cursor", "spawnable"},
    subgroup = "tool",
    order = "d[droid-control]-s[selection]",
    stack_size = 1,
    stackable = false,
	select={ 
		border_color = { r = 0, g = 1, b = 0 },
		mode = {"same-force"},
		cursor_box_type = "not-allowed",
	},
	alt_select={
		border_color = { r = 0, g = 1, b = 0 },
		mode = {"same-force"},
		cursor_box_type = "not-allowed"
	},
  },
  -- This allows loading the selection-tool type item when mods are removed
  {
    type = "selection-tool",
    name = "droid-pickup-tool",
    icon_size = 64,
    icon = ICONPATH .. "pickup_tool.png",
    flags =  {"only-in-cursor", "spawnable"},
    subgroup = "tool",
    order = "d[droid-control]-p[pickup]",
    stack_size = 1,
    stackable = false,
	select={    
		border_color = { r = 1, g = 0, b = 0 },
		mode = {"blueprint"},
		cursor_box_type = "not-allowed",
	},
	alt_select={
		border_color = { r = 1, g = 0, b = 0 },
		mode = {"blueprint"},
		cursor_box_type = "not-allowed"
	},

  },
}
for _, v in pairs(a) do
	data:extend({v})
end